=== uo300652/sew/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">

	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fecha" />
				<xs:element ref="horaInicio" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidadProxima" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="tiempoVencedor" />
				<xs:element ref="clasificados" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="10000"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" type="xs:decimal" use="required" />
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />
	<xs:element name="numeroVueltas">
		<xs:simpleType>
			<xs:restriction base="xs:positiveInteger">
				<xs:minInclusive value="15"/>
				<xs:maxInclusive value="35"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="localidadProxima" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="fuente" type="xs:string" use="required" />
					<xs:attribute name="enlace" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:attribute name="url" type="xs:string" use="required" />
			<xs:attribute name="descripcion" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:attribute name="url" type="xs:string" use="required" />
			<xs:attribute name="descripcion" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="punto" />
				<xs:element ref="distancia" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="-180"/>
								<xs:maxInclusive value="180"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="-90"/>
								<xs:maxInclusive value="90"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="unidad" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="5000"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" type="xs:decimal" use="required" />
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:integer" />
	<xs:element name="vencedor" type="xs:string" />
	<xs:element name="tiempoVencedor" type="xs:duration" />
	<xs:element name="clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado" type="xs:string" />
</xs:schema>

=== uo300652/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
>
    <nombre>Chang International Circuit</nombre>
    <longitud cantidad="4554" unidad="metros"></longitud>
    <anchuraMedia cantidad="12" unidad="metros"></anchuraMedia>
    <fecha>2025-03-02</fecha>
    <horaInicio>14:00:00+07:00</horaInicio>
    <numeroVueltas>26</numeroVueltas>
    <localidadProxima>Buriram</localidadProxima>
    <pais>Tailandia</pais>
    <patrocinador>PTT</patrocinador>

    <referencias>
        <referencia fuente="Wikipedia" enlace="https://es.wikipedia.org/wiki/Circuito_Internacional_de_Chang">
            Ofrece información detallada sobre el circuito, incluyendo su ubicación, características y eventos importantes.
        </referencia>
        <referencia fuente="Vetkuro" enlace="https://vetkuro.com/tracks/buriram">
            Presenta una descripción del circuito, su infraestructura y su historia en el ámbito del automovilismo.
        </referencia>
        <referencia fuente="Motorsport Guides" enlace="https://motorsportguides.com/chang-international-circuit/">
            El Chang International Circuit es un moderno circuito de carreras situado en Buriram, Tailandia. Inaugurado en 2014, es el primer circuito en Tailandia con certificación FIA Grado 1 y FIM Grado A.
        </referencia>
    </referencias>

    <fotografias>
        <fotografia url="./multimedia/LineaDeMeta.jpg" descripcion="Fotografia de la linea de meta"/>
         <fotografia url="./multimedia/LineaDeMetaCarrera.jpg" descripcion="Fotografia de la linea de meta mientras que trascurre una carrera"/>
          <fotografia url="./multimedia/Panorama.jpg" descripcion="Fotografia de la vista general del Chang International Circuit" />
    </fotografias>

    <videos>
        <video url="./multimedia/ChangInternationalCircuit_video.mp4" />
    </videos>

    <puntoOrigen>
        <longitudPunto cantidad="103.084631" unidad="grados"></longitudPunto>
        <latitud cantidad="14.958563" unidad="grados"></latitud>
        <altitud cantidad="179.77" unidad="metros"></altitud>
    </puntoOrigen>

    <tramos>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.082247" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959690" unidad="grados"></latitud>
                <altitud cantidad="179.16" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="283.61" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083470" unidad="grados"></longitudPunto>
                <latitud cantidad="14.964903" unidad="grados"></latitud>
                <altitud cantidad="173" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="584.32" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084025" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968619" unidad="grados"></latitud>
                <altitud cantidad="167.82" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="87.63" unidad="metros"></distancia>
            <sector>3</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084777" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968329" unidad="grados"></latitud>
                <altitud cantidad="165.06" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="841.73" unidad="metros"></distancia>
            <sector>4</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083690" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960774" unidad="grados"></latitud>
                <altitud cantidad="179" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="298.93" unidad="metros"></distancia>
            <sector>5</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085667" unidad="grados"></longitudPunto>
                <latitud cantidad="14.958882" unidad="grados"></latitud>
                <altitud cantidad="177.61" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="118.53" unidad="metros"></distancia>
            <sector>6</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086256" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959800" unidad="grados"></latitud>
                <altitud cantidad="181.7" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="85.39" unidad="metros"></distancia>
            <sector>7</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085879" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960500" unidad="grados"></latitud>
                <altitud cantidad="178.09" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="120.36" unidad="metros"></distancia>
            <sector>8</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084886" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960964" unidad="grados"></latitud>
                <altitud cantidad="179.88" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="73.48" unidad="metros"></distancia>
            <sector>9</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084669" unidad="grados"></longitudPunto>
                <latitud cantidad="14.961595" unidad="grados"></latitud>
                <altitud cantidad="178.26" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="313.35" unidad="metros"></distancia>
            <sector>10</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085056" unidad="grados"></longitudPunto>
                <latitud cantidad="14.964415" unidad="grados"></latitud>
                <altitud cantidad="174.18" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="187.58" unidad="metros"></distancia>
            <sector>11</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086766" unidad="grados"></longitudPunto>
                <latitud cantidad="14.964663" unidad="grados"></latitud>
                <altitud cantidad="174.6" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="83.26" unidad="metros"></distancia>
            <sector>12</sector> 
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.087113" unidad="grados"></longitudPunto>
                <latitud cantidad="14.964016" unidad="grados"></latitud>
                <altitud cantidad="85.96" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="83.26" unidad="metros"></distancia>
            <sector>13</sector>
            
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086440" unidad="grados"></longitudPunto>
                <latitud cantidad="14.963282" unidad="grados"></latitud>
                <altitud cantidad="177.2" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="108.43" unidad="metros"></distancia>
            <sector>14</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086412" unidad="grados"></longitudPunto>
                <latitud cantidad="14.962486" unidad="grados"></latitud>
                <altitud cantidad="177.81" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="85.98" unidad="metros"></distancia>
            <sector>15</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086906" unidad="grados"></longitudPunto>
                <latitud cantidad="14.961632" unidad="grados"></latitud>
                <altitud cantidad="176.85" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="112.36" unidad="metros"></distancia>
            <sector>16</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.087104" unidad="grados"></longitudPunto>
                <latitud cantidad="14.957483" unidad="grados"></latitud>
                <altitud cantidad="177.75" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="461.39" unidad="metros"></distancia>
            <sector>17</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084631" unidad="grados"></longitudPunto>
                <latitud cantidad="14.958563" unidad="grados"></latitud>
                <altitud cantidad="179.78" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="85.98" unidad="metros"></distancia>
            <sector>18</sector>
        </tramo>
    </tramos>

    <vencedor>Marc Márquez</vencedor>
    <tiempoVencedor>PT1M30.637S</tiempoVencedor>

    <clasificados>
        <clasificado>Marc Márquez</clasificado>
        <clasificado>Álex Márquez</clasificado>
        <clasificado>Francesco Bagnaia</clasificado>
